/* @bruin
name: analytics.product_performance
type: duckdb.sql
materialization:
   type: table
depends:
   - fct_order_items
   - dim_products

columns:
  - name: product_id
    type: varchar
    description: "Unique product identifier"
    checks:
      - name: not_null
      - name: unique
  - name: category
    type: varchar
    description: "Product category"
    checks:
      - name: not_null
      - name: accepted_values
        value: ["Electronics", "Books", "Clothing", "Home & Garden", "Toys"]
  - name: total_revenue
    type: decimal
    description: "Total revenue generated by this product"
    checks:
      - name: not_null
  - name: units_sold
    type: bigint
    description: "Total units sold"
    checks:
      - name: not_null
  - name: avg_price
    type: decimal
    description: "Average selling price"

custom_checks:
  - name: revenue_matches_calculation
    query: |
      SELECT COUNT(*) as issue_count
      FROM analytics.product_performance
      WHERE ABS(total_revenue - (units_sold * avg_price)) > 0.01
      AND units_sold > 0
    value: 0

@bruin */

SELECT 
    p.product_id,
    p.name AS product_name,
    p.category,
    p.current_price,
    COALESCE(SUM(oi.total_item_amount), 0) AS total_revenue,
    COALESCE(SUM(oi.quantity), 0) AS units_sold,
    COALESCE(AVG(oi.price_at_purchase), 0) AS avg_price,
    COUNT(DISTINCT oi.order_id) AS order_count,
    MIN(oi.updated_at) AS first_sale_date,
    MAX(oi.updated_at) AS last_sale_date
FROM dim_products p
LEFT JOIN fct_order_items oi ON p.product_id = oi.product_id
GROUP BY 
    p.product_id,
    p.name,
    p.category,
    p.current_price
