name: raw.products
type: ingestr
parameters:
  destination: duckdb
  source_connection: oltp
  source_table: public.products
  incremental_strategy: merge

columns:
  - name: id
    type: varchar
    primary_key: true
    description: "Unique product identifier"
  - name: current_price
    type: decimal
    description: "Current product price"
  - name: category
    type: varchar
